spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/spring_cache?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
        password: Pa$$w0rd
        username: root
    redis:
        host: 109.116.6.127
        port: 6379
        password: Pa$$w0rd
mybatis:
    configuration:
        mapUnderscoreToCamelCase: true
server:
    port: 7070
