spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/spring_cache?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
        password: Pa$$w0rd
        username: root
    redis:
        host: 192.168.233.128
        port: 6379
        password: Pa$$w0rd
        timeout: 10000
        database: 0
        lettuce:
            pool:
                max-active: 8
                max-wait: -1
                max-idle: 8
                min-idle: 0
mybatis:
    configuration:
        mapUnderscoreToCamelCase: true
server:
    port: 7070
